### ISSUE TITLE
Auto dropping ''unfamiliar item''.

### ISSUE THREAD

**Issue by AChubbyPinkFluffyFabWhale** [AshenGaming/spellbreak#3]
#### Please format the title as such: 
[Spellbreak Version] Mod Name - Issue
Version: 0.1 

----

#### Mods Involved:
Please list all the mods involved in this issue:
- Mod : Soulus (Atleast this is were i have the item from. if there is another mod with ''Unfamiliar item i think it would do the same)

#### Issue type:
Please select one of the below options and delete any additional ones.
- Config Issue

#### Short description:
What is the bug/config issue?
Items called: 'Unfamiliar item' is auto dropping when its in your hotbar.
#### Expected behaviour:
What would you expect to happen during normal gameplay?
it should stay in mine inventory/hotbar.

#### Actual behaviour:
What actually happens?
it Auto drops when its in your hotbar
If the auto drop is normal, Then you still have another issue:
The autodrop only works if its in your hotbar if it isn't in your hotbar it wont drop.

#### Steps to reproduce the problem:
1. Just open ''Ender bone chunks'' after a few tries you will get a 'Unfamiliar item'' if you place this in your hotbar then it autodrops.

#### Additional Information:

![image](https://user-images.githubusercontent.com/34548365/43539034-fd90a51a-95c3-11e8-8106-3fe635a2696f.png)

____
#### Mod Versions:

- Modpack:  *E.g. Spellbreak v0.1*
- Mod in Question: *E.g. Agricraft v1.12-0.1.4, Anima Mundi v1.12-0.2.1*
- Forge:  *E.g. 14.2.3.2739*

**Comment by AChubbyPinkFluffyFabWhale** [comment]
This auto dropping  will only happen if you try holding it in your hand. This could be a problem regarding the quest : ''Less-Friendly essences''.

**Comment by AshenGaming** [comment]
This is intentional (at least as far as the staging goes). The way around it is to store it from your inventory without holding it. This can't be changed on my end.
