### ISSUE TITLE
Some mobs can spawn before entering the Nether.

### ISSUE THREAD

**Issue by AChubbyPinkFluffyFabWhale** [AshenGaming/spellbreak#4]
#### Please format the title as such: 
[Spellbreak Version] Mod Name - Issue

----

#### Mods Involved:
Please list all the mods involved in this issue:
- Mod 1: Thaumcraft
- Mod 2: Embers
- Mod 3: Minecraft (Not 100% sure if this is also not allowed)

#### Issue type:
Please select one of the below options and delete any additional ones.

- Config Issue

#### Short description:
What is the bug/config issue?
Some mobs can spawn before entering the nether,
#### Expected behaviour:
What would you expect to happen during normal gameplay?
They won't spawn before going to the Nether

#### Actual behaviour:
What actually happens?
they can spawn

#### Steps to reproduce the problem:
Thaumcraft mobs:
1. Here is where you write the steps you took to reproduce.
Make a world or find a Thaumcraft portal.
2. If you weren't able to reproduce the problem, state so here
It can be annoying to ''natural'' find them. A ''lesser crimson Portal' was the object that summons them. 

Embers mod:
Find a 3x3 Embers place (the one made from Ashen tiles and Archaic Bricks.
There should be a Ancient golem.

Minecraft (Not 100% sure if this is intented or not):
Get chicken eggs from Bird nests 
Throw the chicken eggs.
#### Additional Information:

![image](https://user-images.githubusercontent.com/34548365/43539584-9122008e-95c5-11e8-9a3a-69ce640fed61.png)

____
#### Mod Versions:

- Modpack:  E.g. Spellbreak v0.1
- Mod in Question: Minecraft (Config regarding chicken spawn from eggs)l;
- Thaumcraft version: 1.12.2-6.1.BETA19;
- Embers version: 0.230;
- Forge version: 14.23.4.2739

**Comment by AChubbyPinkFluffyFabWhale** [comment]
Witch and Ancient golem can also can spawn before entering the nether, 
Its hard to recreate this but i made a automated system with Command blocks to make it night after a while kill NPC's (cofh command), make it day after a while the Kill NPC. this system is on a loop.

**Comment by AshenGaming** [comment]
It wouldn't be done via command blocks anyway, but if the witch and the ancient golem from embers is still spawning then there's an issue with either the script, or your install. I had the golems and such working before hand. I'll investigate on my end.

**Comment by AshenGaming** [comment]
Just to clarify, have you actually seen these mobs in the game? As in, have you actually seen a witch and ancient golem before doing the nether questline? Or are you just relying on the output from the command block?

**Comment by AChubbyPinkFluffyFabWhale** [comment]
I did typ the ''Cofh killall'' command from that i got the sentence that a witch and 2 ancient golems got killed.

**Comment by AChubbyPinkFluffyFabWhale** [comment]
According to ''Zurt message'' in the discord, is it possible for Pirates to spawn from the mod Quark.

**Comment by AshenGaming** [comment]
Reported the villagers spawning to mod author, going to see if this is a similar issue with the rest of the mobs not being staged correctly.
https://github.com/Darkhax-Minecraft/MobStages/issues/3

**Comment by AshenGaming** [comment]
Looks like this is intentional, due to how Villagers are "spawned". They actually generate with the structures, so I'll have to create a "fake" Overworld for the player to start in. Shouldn't be *too* difficult, but we'll see. I'll add it to the to-do list and close this for now. I'll re-open for the other mobs later.
