### ISSUE TITLE
[FEEDBACK] Related to the modpack

### ISSUE THREAD

**Issue by AChubbyPinkFluffyFabWhale** [AshenGaming/spellbreak#5]
Feedback regarding the first 10 minutes of the game:

At the start of the game when you have done a few quests just before you can summon mobs using Soulus mod. You might run into the issue you don't have any food because mobs can't spawn so it would me nice of having a small bit of food for exploring. for example by doing a small quest.

**Comment by AChubbyPinkFluffyFabWhale** [comment]
Is there a possibility to change the recipe of the ''holy hand grenade'' to something more expensive; 
(it cost 1 tnt, 1 catalyzing gland, 1 Glowing water and 1 gold nugget) Which is pretty cheap in comparison  with the damage it will deliver.

**Comment by AshenGaming** [comment]
Food I'll take a look at, see if I can work the birds nests into that issue. Of course there is still seeds/wheat/bread that you can grow and craft. In regards to the holy hand grenade, I'll look at the recipe soon, but I haven't done any modified recipes yet.

**Comment by AChubbyPinkFluffyFabWhale** [comment]
If you work ''Raw Chicken/bird'' into bird nest as a uncommon item would be nice.
But from the other side you can ''semi-force'' people to not rush the modpack by making a small farm first.

**Comment by AshenGaming** [comment]
Working on better food supplies (WIP) and I'm still looking into the spawning. Will close this for now, as I've narrowed down the issues.
