### ISSUE TITLE
Embers Block breaker crashed SP

### ISSUE THREAD

**Issue by AChubbyPinkFluffyFabWhale** [AshenGaming/spellbreak#6]
#### Please format the title as such: 
Embers Block breaker crashed SP

----

#### Mods Involved:
Please list all the mods involved in this issue:
- Mod 1: Embers
-

#### Issue type:
Please select one of the below options and delete any additional ones.
- Bug

#### Short description:
What is the bug/config issue?
If you stack two block breakers on each other it crash the server
#### Expected behaviour:
What would you expect to happen during normal gameplay?
that the most above block would be destroyed

#### Actual behaviour:
What actually happens?
it crashes mine game.

#### Steps to reproduce the problem:
Stack two block breakers on each other from the mod Embers
1. Here is where you write the steps you took to reproduce.
2. If you weren't able to reproduce the problem, state so here.

#### Additional Information:
https://paste.dimdev.org/ebujahofib.mccrash

____
#### Mod Versions:

- Modpack: E.g. Spellbreak v0.1 Pre-Alpha
- Mod in Question: Embers Version: 0.230

- Forge:  E.g. 14.23:4:2739

**Comment by AshenGaming** [comment]
Please make sure to fill in the versions at the bottom of the template, otherwise I can't track stuff properly :)

**Comment by AChubbyPinkFluffyFabWhale** [comment]
Changed the bottom part of the template (gonna change it on the other threads)

**Comment by AshenGaming** [comment]
Fixed in v0.1.2a.
