### ISSUE TITLE
Superflat customization 

### ISSUE THREAD

**Issue by AChubbyPinkFluffyFabWhale** [AshenGaming/spellbreak#7]
#### Please format the title as such: 
[Spellbreak Version] Mod Name - Issue

----

#### Mods Involved:
Please list all the mods involved in this issue:
- Mod #1 The world generator mod (Don't know the official name of the mod)
- Mod #2

#### Issue type:
Please select one of the below options and delete any additional ones.
- Bug

#### Short description:
What is the bug/config issue?
When you make a custom superflat world there is still a chance for pools, ores and other things to generated.
#### Expected behaviour:
What would you expect to happen during normal gameplay?
That this wouldn't happened only if this checked on. 

#### Actual behaviour:
What actually happens?
When you make a custom superflat world there is still a chance for pools, ores and other things to generated.

#### Steps to reproduce the problem:

1. Here is where you write the steps you took to reproduce.
1. Make a world;
2. Choose the More World option;
3. Change the world type to ''Superflat'';
4. Press Customize;
5. press Presents;
6. Change the Top bar to a custom layout for example: ''3;1*minecraft:bedrock,50*minecraft:stone,1*minecraft:stone_slab:5;2;village''
7. Starts the map
2. If you weren't able to reproduce the problem, state so here.

**Comment by AshenGaming** [comment]
I looked into this, and it appears that most mods will generate their content _after_ the terrain generation takes place, meaning that the preset will have no effects on this content. Not much I can do about it unfortunately.
